# Generated by Django 2.2.2 on 2019-06-30 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 6, 30, 13, 0, 55, 621355, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
